# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 124850233bf26e8846169ffbb421829ea8f894c43cc2bca97019be3aafbe0ad3ee2c5cbe033d868422cba7dc4e7b5307af858b99984b0d7552f9ca575fa201f2

test:
  secret_key_base: e5527354cc4c13f576431ff9157597e47867abb8fc90dee84662e59c839c070ec5fe7401106be5d334617d23766786e017cc2c1c3b8866ff620910af8a49a2cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
